version: '3'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: jobs
      POSTGRES_DATABASE: jobs
      POSTGRES_PASSWORD: supsupsup
    volumes:
      - devict-jobs-pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    env_file: .env
    environment:
      DATABASE_URL: "postgres://jobs:supsupsup@db:5432/jobs"
      APP_SECRET: "itsasecret"
      APP_ENV: "debug"
      FROM_EMAIL: "test@localhost"
    volumes:
      - .:/app
    ports:
      - 8080:8080

volumes:
  devict-jobs-pgdata:
